---
services:
  ubuntu:
    image: mcr.microsoft.com/devcontainers/universal:linux
    container_name: ubuntu
    restart: unless-stopped
    volumes:
      - ..:/workspace:cached

  webspace:
    image: ghcr.io/simonhaas/images/webspace:main
    container_name: webspace
    #security_opt:
    #  - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3000:3000
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    shm_size: "1gb"
    restart: unless-stopped
