---
services:
  ubuntu:
    image: mcr.microsoft.com/devcontainers/universal:linux
    container_name: ubuntu
    restart: unless-stopped
    volumes:
      - ..:/workspace:cached

  webtop:
    # image: lscr.io/linuxserver/webtop:latest
    build: .
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    ports:
      - 3000:3000
    # devices:
    #  - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
